try{
    console.log(a);
}
catch{
    console.log("Error");
}